# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/ssd2/work/Unreal_Engine_5.5

TARGETS = \
	TudiAnalyticsTest-Android-DebugGame  \
	TudiAnalyticsTest-Android-Development  \
	TudiAnalyticsTest-Android-Shipping  \
	TudiAnalyticsTest-Linux-DebugGame  \
	TudiAnalyticsTest-Linux-Development  \
	TudiAnalyticsTest-Linux-Shipping  \
	TudiAnalyticsTest-LinuxArm64-DebugGame  \
	TudiAnalyticsTest-LinuxArm64-Development  \
	TudiAnalyticsTest-LinuxArm64-Shipping  \
	TudiAnalyticsTest \
	TudiAnalyticsTestEditor-Linux-DebugGame  \
	TudiAnalyticsTestEditor-Linux-Development  \
	TudiAnalyticsTestEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend TudiAnalyticsTestEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug TudiAnalyticsTestEditor-Linux-Debug


TudiAnalyticsTest-Android-DebugGame:
	 $(BUILD) TudiAnalyticsTest Android DebugGame  -Project="/opt/ssd2/work/TudiAnalyticsTest/TudiAnalyticsTest.uproject" $(ARGS)

TudiAnalyticsTest-Android-Development:
	 $(BUILD) TudiAnalyticsTest Android Development  -Project="/opt/ssd2/work/TudiAnalyticsTest/TudiAnalyticsTest.uproject" $(ARGS)

TudiAnalyticsTest-Android-Shipping:
	 $(BUILD) TudiAnalyticsTest Android Shipping  -Project="/opt/ssd2/work/TudiAnalyticsTest/TudiAnalyticsTest.uproject" $(ARGS)

TudiAnalyticsTest-Linux-DebugGame:
	 $(BUILD) TudiAnalyticsTest Linux DebugGame  -Project="/opt/ssd2/work/TudiAnalyticsTest/TudiAnalyticsTest.uproject" $(ARGS)

TudiAnalyticsTest-Linux-Development:
	 $(BUILD) TudiAnalyticsTest Linux Development  -Project="/opt/ssd2/work/TudiAnalyticsTest/TudiAnalyticsTest.uproject" $(ARGS)

TudiAnalyticsTest-Linux-Shipping:
	 $(BUILD) TudiAnalyticsTest Linux Shipping  -Project="/opt/ssd2/work/TudiAnalyticsTest/TudiAnalyticsTest.uproject" $(ARGS)

TudiAnalyticsTest-LinuxArm64-DebugGame:
	 $(BUILD) TudiAnalyticsTest LinuxArm64 DebugGame  -Project="/opt/ssd2/work/TudiAnalyticsTest/TudiAnalyticsTest.uproject" $(ARGS)

TudiAnalyticsTest-LinuxArm64-Development:
	 $(BUILD) TudiAnalyticsTest LinuxArm64 Development  -Project="/opt/ssd2/work/TudiAnalyticsTest/TudiAnalyticsTest.uproject" $(ARGS)

TudiAnalyticsTest-LinuxArm64-Shipping:
	 $(BUILD) TudiAnalyticsTest LinuxArm64 Shipping  -Project="/opt/ssd2/work/TudiAnalyticsTest/TudiAnalyticsTest.uproject" $(ARGS)

TudiAnalyticsTest: TudiAnalyticsTest-Linux-Development

TudiAnalyticsTestEditor-Linux-DebugGame:
	 $(BUILD) TudiAnalyticsTestEditor Linux DebugGame  -Project="/opt/ssd2/work/TudiAnalyticsTest/TudiAnalyticsTest.uproject" $(ARGS)

TudiAnalyticsTestEditor-Linux-Development:
	 $(BUILD) TudiAnalyticsTestEditor Linux Development  -Project="/opt/ssd2/work/TudiAnalyticsTest/TudiAnalyticsTest.uproject" $(ARGS)

TudiAnalyticsTestEditor: TudiAnalyticsTestEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/opt/ssd2/work/TudiAnalyticsTest/TudiAnalyticsTest.uproject" -Game 

.PHONY: $(TARGETS)
